name: kater
description: Official Kater App for Mobile
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2

dev_dependencies:
  html: ^0.14.0+3
  url_launcher: ^5.4.11
  pull_to_refresh: ^1.5.7
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/images/logo.png
    - res/images/avatar.png

flutter_launcher_name:
  name: Kater

flutter_icons:
  image_path: res/images/logo.png
  android: true
  ios: true
